document: feedback-pipeline-workload
version: 1
data:
  name: meta-sig packages
  description: ELN Extras packages that Meta cares about
  maintainer: meta-sig

  packages:
  - atop
  - awscli
  - azure-cli
  - b4
  - below
  - btrd
  - ccache
  - colm
  - ctags
  - dbench
  - debian-keyring
  - debootstrap
  - dnf5
  - dpkg
  - drgn
  - duo_unix
  - duo_unix-selinux
  - ebranch
  - et
  - htop
  - iotools
  - fping
  - keyrings-filesystem
  - lei
  - libdwarf
  - libdwarf-devel
  - libkdumpfile-devel
  - libidn
  - libidn-devel
  - mkosi
  - mosh
  - ncdu
  - neovim
  - netconsd
  - ngrep
  - packetdrill
  - packetdrill-data
  - pam_duo
  - pam_krb5
  - parallel
  - pngquant
  - pv
  - python3-dnf-plugin-flunk_dependent_remove
  - python3-pystemd
  - python3-testslide
  - rpmdistro-repoquery
  - rpminspect
  - rpminspect-data-centos
  - rpminspect-data-fedora
  - rpmrebuild
  - qrencode-devel
  - ragel
  - retsnoop
  - ripgrep
  - screen
  - sdparm
  - sedutil
  - sequoia-keyring-linter
  - sysbench
  - stress
  - stressapptest
  - strongswan
  - tpm-tools
  - ubu-keyring
  - veristat

  arch_packages:
    i686:
      - msr-tools
    x86_64:
      - msr-tools

  labels:
  - eln-extras
