document: feedback-pipeline-workload
version: 1
data:
  name: hyperscale packages
  description: ELN Extras packages that the CentOS Hyperscale SIG cares about
  maintainer: sig-hyperscale

  packages:
  - btrfs-fuse
  - centos-packager
  - fsverity-utils
  - iptables-legacy
  - iptables-legacy-devel
  - iptables-legacy-libs
  - iptables-services
  - mock-centos-sig-configs
  - systemd-networkd

  labels:
  - eln-extras
