document: feedback-pipeline-workload
version: 1
data:
  name: GNOME Text Editor
  description: Text editor for Workstation
  maintainer: sst_desktop

  packages:
  - gnome-text-editor

  labels:
  - eln
