document: feedback-pipeline-workload
version: 1
data:
  name: tbb
  description: Threading Building Blocks library
  maintainer: sst_platform_tools

  packages:
  - python3-tbb
  - tbb
  - tbb-devel
  - tbb-doc

  labels:
  - c9s
