---
document: feedback-pipeline-workload
version: 1
data:
  name: IBus GTK2 input methods
  description: Archive GTK2 i18n metapackages.
  maintainer: sst_i18n
  labels:
  - c9s
  packages:
  - gtk2-immodule-xim
  - ibus-gtk2
