document: feedback-pipeline-workload
version: 1
data:
  name: HA
  description: HA needed packages
  maintainer: sst_high_availability

  packages: []

  package_placeholders:
  - srpm_name: fence-agents
    build_dependencies: []
    limit_arches:
    - x86_64
    - ppc64le
    - s390x
    rpms:
    - rpm_name: fence-agents-aliyun
      description: This package is only provided in RHEL
  - srpm_name: pcs
    build_dependencies:
    - booth
    - corosync-qdevice-devel
    - corosynclib-devel
    - diffstat
    - fence-agents-common
    - git-core
    - make
    - npm
    - pacemaker-libs-devel
    - pam
    - python3-cryptography
    - python3-dateutil
    - python3-devel
    - python3-setuptools
    - python3-pycurl
    - python3-pip
    - python3-pyparsing
    - python3-lxml
    - python3-wheel
    - python3-setuptools_scm
    - redhat-logos
    - resource-agents
    - ruby-devel
    - rubygems
    - rubygem-bundler
    - rubygem-json
    - rubygem-rexml
    - rubygem-test-unit
    - sbd
    limit_arches:
    - x86_64
    - ppc64le
    - s390x
    rpms:
    - rpm_name: pcs
      description: Built with bundled dependencies in RHEL
      requires:
        - corosync
        - libknet1-plugins-all
        - pacemaker-cli
        - pam
        - pcmk-cluster-manager
        - psmisc
        - python3
        - python3-cryptography
        - python3-dateutil
        - python3-lxml
        - python3-pycurl
        - python3-pyparsing
        - python3-setuptools
        - redhat-logos
        - ruby
        - rubygem-json
        - rubygem-rexml
        - rubygems
      limit_arches:
        - x86_64
        - ppc64le
        - s390x
    - rpm_name: pcs-snmp
      description: Built with bundled dependencies in RHEL
      requires:
        - net-snmp
        - pacemaker
        # pcs (placeholder)
      limit_arches:
        - x86_64
        - ppc64le
        - s390x
  - srpm_name: python-gflags
    build_dependencies:
    - python3-devel
    rpms:
    - rpm_name: python3-gflags
      description: This package is only provided in RHEL
      dependencies:
      - python3      
  - srpm_name: resource-agents
    build_dependencies: []
    limit_arches: []
    rpms:
    - rpm_name: resource-agents-cloud
      description: This package is only provided in RHEL
      dependencies:
      # ha-cloud-support (placeholder)
      - socat
      limit_arches:
      - x86_64

  arch_packages:
    # No packages from HA currently support aarch64.
    # aarch64:

    ppc64le:
    - booth
    - booth-arbitrator
    - booth-core
    - booth-site
    - booth-test
    - corosync-qdevice
    - corosync-qnetd
    - corosynclib-devel
    - fence-agents-all
    - fence-virt
    - fence-virtd
    - fence-virtd-libvirt
    - fence-virtd-multicast
    - fence-virtd-serial
    - fence-virtd-tcp
    - haproxy
    - ipvsadm
    - keepalived
    - libknet1
    - libknet1-compress-bzip2-plugin
    - libknet1-compress-lz4-plugin
    - libknet1-compress-lzma-plugin
    - libknet1-compress-lzo2-plugin
    - libknet1-compress-plugins-all
    - libknet1-compress-zlib-plugin
    - libknet1-crypto-openssl-plugin
    - libknet1-crypto-plugins-all
    - libknet1-devel
    - libknet1-plugins-all
    - libnozzle1
    - libnozzle1-devel
    - omping
    - pacemaker-cts
    - pacemaker-doc
    - pacemaker-libs-devel
    - pacemaker-nagios-plugins-metadata
    - pacemaker-remote
    - resource-agents
    - sbd
    - spausedd

    s390x:
    - booth
    - booth-arbitrator
    - booth-core
    - booth-site
    - booth-test
    - corosync-qdevice
    - corosync-qnetd
    - corosynclib-devel
    - fence-agents-all
    - fence-virt
    - fence-virtd
    - fence-virtd-libvirt
    - fence-virtd-multicast
    - fence-virtd-serial
    - fence-virtd-tcp
    - haproxy
    - ipvsadm
    - keepalived
    - libknet1
    - libknet1-compress-bzip2-plugin
    - libknet1-compress-lz4-plugin
    - libknet1-compress-lzma-plugin
    - libknet1-compress-lzo2-plugin
    - libknet1-compress-plugins-all
    - libknet1-compress-zlib-plugin
    - libknet1-crypto-openssl-plugin
    - libknet1-crypto-plugins-all
    - libknet1-devel
    - libknet1-plugins-all
    - libnozzle1
    - libnozzle1-devel
    - omping
    - pacemaker-cts
    - pacemaker-doc
    - pacemaker-libs-devel
    - pacemaker-nagios-plugins-metadata
    - pacemaker-remote
    - resource-agents
    - sbd
    - spausedd

    x86_64:
    - booth
    - booth-arbitrator
    - booth-core
    - booth-site
    - booth-test
    - corosync-qdevice
    - corosync-qnetd
    - corosynclib-devel
    - fence-agents-all
    - fence-virt
    - fence-virtd
    - fence-virtd-libvirt
    - fence-virtd-multicast
    - fence-virtd-serial
    - fence-virtd-tcp
    - haproxy
    - ipvsadm
    - keepalived
    - libknet1
    - libknet1-compress-bzip2-plugin
    - libknet1-compress-lz4-plugin
    - libknet1-compress-lzma-plugin
    - libknet1-compress-lzo2-plugin
    - libknet1-compress-plugins-all
    - libknet1-compress-zlib-plugin
    - libknet1-crypto-openssl-plugin
    - libknet1-crypto-plugins-all
    - libknet1-devel
    - libknet1-plugins-all
    - libnozzle1
    - libnozzle1-devel
    - omping
    - pacemaker-cts
    - pacemaker-doc
    - pacemaker-libs-devel
    - pacemaker-nagios-plugins-metadata
    - pacemaker-remote
    - resource-agents
    - sbd
    - spausedd

  labels:
  - eln
  - c9s
