document: feedback-pipeline-workload
version: 1
data:
  name: Scanning Stack GUI for C9S
  description: Suite of software needed for scanning on Linux
  maintainer: sst_cs_infra_services

  packages:
  # uses gtk2 which is being removed in RHEL 10
  - xsane

  labels:
  - c9s
