document: feedback-pipeline-workload
version: 1
data:
  name: Rust Toolset
  description: Collection of packages providing the rust compiler toolchain.
  maintainer: sst_platform_tools

  packages:
  - rust
  - cargo
  - clippy
  - rust-analyzer
  - rust-doc
  - rust-std-static
  - rustfmt
  - rust-srpm-macros
  - rust-toolset

  labels:
  - eln
  - c9s
